Author: Vaasudevan Srinivasan <br>
Created on: June 20, 2021

In [ ]:
import tensorflow as tf
import tensorflow_probability as tfp
import numpy as np
tf.__version__

'2.5.0'

# Creating your first tensors with TensorFlow and `tf.constant`

In [ ]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
matrix = tf.constant([[10, 2],
                      [60, 70]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  2],
       [60, 70]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
matrix1 = tf.constant([[10, 2],
                      [60, 70],
                       [90, 100]], dtype=tf.float16)
matrix1

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 10.,   2.],
       [ 60.,  70.],
       [ 90., 100.]], dtype=float16)>

# Creating tensors with TensorFlow and `tf.Variable`

In [ ]:
changable_tensor = tf.Variable([10, 20])
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 20], dtype=int32)>

In [ ]:
changable_tensor[0].assign(30)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([30, 20], dtype=int32)>

# Creating random tensors with TensorFlow

In [ ]:
random_gen = tf.random.Generator.from_seed(96)
random_tensor1 = random_gen.normal(shape=(3, 2))
random_tensor1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.02589307,  1.1928992 ],
       [ 1.7263643 ,  0.7151379 ],
       [-1.0779938 , -1.1893024 ]], dtype=float32)>

In [ ]:
random_tensor1.numpy()

array([[-0.02589307,  1.1928992 ],
       [ 1.7263643 ,  0.7151379 ],
       [-1.0779938 , -1.1893024 ]], dtype=float32)

# Shuffling the order of tensors

In [ ]:
not_shuffled = tf.constant([[1, 2],
                            [3, 4],
                            [5, 6]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [ ]:
tf.random.set_seed(96)
tf.random.shuffle(not_shuffled, seed=97)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [1, 2],
       [5, 6]], dtype=int32)>

# Creating tensors from NumPy arrays

In [ ]:
tf.ones([3, 2])

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [ ]:
arr = np.arange(10)
tf.constant(arr)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [ ]:
tf.constant(arr, shape=(2, 5))

<tf.Tensor: shape=(2, 5), dtype=int64, numpy=
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])>

# Getting information from your tensors (tensor attributes)

In [ ]:
rank4_tensor = tf.zeros(shape=(2, 3, 4, 5))
rank4_tensor.ndim, rank4_tensor.shape, tf.size(rank4_tensor)

(4, TensorShape([2, 3, 4, 5]), <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
rank4_tensor.numpy().shape

(2, 3, 4, 5)

# Indexing and expanding tensors

In [ ]:
t1 = tf.ones(shape=(2, 4))
t1[0]

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 1., 1., 1.], dtype=float32)>

In [ ]:
tf.expand_dims(t1, axis=-1)

<tf.Tensor: shape=(2, 4, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]]], dtype=float32)>

# Manipulating tensors with basic operations

In [ ]:
t1 = tf.constant([[10, 20], [30, 40]])
t1 + 1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 21],
       [31, 41]], dtype=int32)>

In [ ]:
# Runs faster than t1 * 17
tf.multiply(t1, 17)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[170, 340],
       [510, 680]], dtype=int32)>

# Matrix multiplication with tensors part 1, part 2, part 3

In [ ]:
tf1 = tf.constant([[1, 2, 3], [4, 5, 6]])
tf2 = tf.constant([[10, 20], [30, 40], [50, 60]])
tf1, tf2

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10, 20],
        [30, 40],
        [50, 60]], dtype=int32)>)

In [ ]:
tf.matmul(tf1, tf2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[220, 280],
       [490, 640]], dtype=int32)>

In [ ]:
tf1 @ tf2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[220, 280],
       [490, 640]], dtype=int32)>

In [ ]:
tf.reshape(tf1, shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [ ]:
tf.transpose(tf1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

In [ ]:
tf.tensordot(tf1, tf2, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[220, 280],
       [490, 640]], dtype=int32)>

In [ ]:
tf1.shape, tf.transpose(tf1).shape

(TensorShape([2, 3]), TensorShape([3, 2]))

# Changing the datatype of tensors

In [ ]:
tf1 = tf.constant([1., 2])
tf1.dtype

tf.float32

In [ ]:
tf2 = tf.constant([3, 4])
tf2.dtype

tf.int32

In [ ]:
tf.cast(tf2, dtype=tf.float16)

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([3., 4.], dtype=float16)>

# Tensor aggregation (finding the min, max, mean & more)

In [ ]:
tf1 = tf.constant([-10, 20])
tf.abs(tf1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20], dtype=int32)>

In [ ]:
tf2 = tf.constant(np.random.randint(0, 500, size=50))
tf2

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 35, 193, 161, 116, 381, 473, 189, 210, 271, 102, 145, 186, 397,
       496, 288, 164, 284,  32, 313, 471, 317, 289, 493, 232,  80, 392,
       132, 378, 390, 230, 266, 467,  71, 302,   6,  39,  45, 472, 179,
       462, 445,  59, 240, 145, 192, 253, 142, 371, 226,  35])>

In [ ]:
tf.size(tf2), tf2.shape, tf2.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
tf.reduce_min(tf2), tf.reduce_max(tf2), tf.reduce_mean(tf2), tf.reduce_sum(tf2)

(<tf.Tensor: shape=(), dtype=int64, numpy=6>,
 <tf.Tensor: shape=(), dtype=int64, numpy=496>,
 <tf.Tensor: shape=(), dtype=int64, numpy=245>,
 <tf.Tensor: shape=(), dtype=int64, numpy=12257>)

In [ ]:
tfp.stats.variance(tf2), tf.math.reduce_std(tf.cast(tf2, dtype=tf.float32))

(<tf.Tensor: shape=(), dtype=int64, numpy=20612>,
 <tf.Tensor: shape=(), dtype=float32, numpy=143.56937>)

# Finding the positional minimum and maximum of a tensor (argmin and argmax)

In [ ]:
tf1 = tf.random.uniform(shape=(2, 5))
tf1

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[0.6984576 , 0.3248868 , 0.137146  , 0.88248765, 0.7347206 ],
       [0.42851925, 0.60055816, 0.4202006 , 0.28532004, 0.7447227 ]],
      dtype=float32)>

In [ ]:
tf.argmax(tf1, axis=1)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([3, 4])>

# Squeezing a tensor (removing all 1-dimension axes)

In [ ]:
tf1 = tf.random.normal(shape=(1, 3))
tf1

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[ 0.29493204, -0.36513406,  0.210189  ]], dtype=float32)>

In [ ]:
tf.squeeze(tf1)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 0.29493204, -0.36513406,  0.210189  ], dtype=float32)>

# One-hot encoding tensors

In [ ]:
some_list = [0, 1, 2, 3]
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
tf.one_hot(some_list, depth=4, on_value='A', off_value='B')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'A', b'B', b'B', b'B'],
       [b'B', b'A', b'B', b'B'],
       [b'B', b'B', b'A', b'B'],
       [b'B', b'B', b'B', b'A']], dtype=object)>

# Trying out more tensor math operations

In [ ]:
tf1 = tf.range(10)
tf1

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(tf1)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
tf.sqrt(tf.cast(tf1, dtype='float16'))

<tf.Tensor: shape=(10,), dtype=float16, numpy=
array([0.   , 1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828,
       3.   ], dtype=float16)>

In [ ]:
tf.math.log(tf.cast(tf1, dtype='float16'))

<tf.Tensor: shape=(10,), dtype=float16, numpy=
array([  -inf, 0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 ,
       2.08  , 2.197 ], dtype=float16)>

# Making sure our tensor operations run really fast on GPUs

In [ ]:
!nvidia-smi

Sun Jun 20 17:38:52 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.27       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   49C    P8    10W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------