In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

torch.__version__

'2.0.1+cu118'

# 15. Introduction to PyTorch Tensors

In [ ]:
scalar = torch.tensor(1996)
scalar

tensor(1996)

In [ ]:
scalar.item()

1996

In [ ]:
vector = torch.tensor([24, 11])
vector

tensor([24, 11])

In [ ]:
vector + 1

tensor([25, 12])

In [ ]:
matrix = torch.tensor([[1, 2], [3, 4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [ ]:
matrix.ndim, matrix.shape

(2, torch.Size([2, 2]))

In [ ]:
matrix[0, 1]

tensor(2)

# 16. Creating Random Tensors in PyTorch

In [ ]:
random_tensor = torch.rand(2, 2, 2)
random_tensor

tensor([[[0.9671, 0.6651],
         [0.7124, 0.5784]],

        [[0.0151, 0.1822],
         [0.2283, 0.3070]]])

In [ ]:
random_tensor.dtype

torch.float32

# 17. Creating Tensors with Zeros and Ones

In [ ]:
ones = torch.ones(3, 3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

# 18. Creating Range of Tensors

In [ ]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arange = torch.arange(10, 20, 0.8)
arange

tensor([10.0000, 10.8000, 11.6000, 12.4000, 13.2000, 14.0000, 14.8000, 15.6000,
        16.4000, 17.2000, 18.0000, 18.8000, 19.6000])

In [ ]:
arange_like = torch.zeros_like(arange)
arange_like

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# 19. Tensor Datatypes

In [ ]:
f32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                          dtype=None,
                          device='cpu',
                          requires_grad=False)

f32_tensor

tensor([3., 6., 9.])

In [ ]:
f32_tensor.type(torch.float16)

tensor([3., 6., 9.], dtype=torch.float16)

# 20. Getting Tensor Attributes

In [ ]:
print(f32_tensor.dtype, f32_tensor.shape, f32_tensor.device)

torch.float32 torch.Size([3]) cpu


# 21. Manipulating Tensors

In [ ]:
tensora = torch.tensor([1, 2, 3])
tensorb = torch.tensor([4, 5, 6])

In [ ]:
tensora + tensorb

tensor([5, 7, 9])

# 22. Matrix Multiplication

In [ ]:
torch.matmul(tensora, tensorb)

tensor(32)

In [ ]:
tensora @ tensorb

tensor(32)

In [ ]:
tensora.T.size()

torch.Size([3])

# 25. Finding Min, Max, Mean, Sum

In [ ]:
tensora = torch.tensor([1, 2, 3], dtype=torch.float32)

In [ ]:
tensora.min(), tensora.max()

(tensor(1.), tensor(3.))

In [ ]:
torch.mean(tensora)

tensor(2.)

In [ ]:
torch.sum(tensora)

tensor(6.)

# 26. Finding the Positional Min and Max of Tensors

In [ ]:
x = torch.rand(4, 2)
x

tensor([[0.4443, 0.7633],
        [0.2352, 0.7933],
        [0.3007, 0.8323],
        [0.7832, 0.7192]])

In [ ]:
x.argmin()

tensor(2)

In [ ]:
x.argmax()

tensor(5)

# 27. Reshaping, Viewing and Stacking Tensors

In [ ]:
x = torch.rand(10)
x

tensor([0.5576, 0.7788, 0.1189, 0.0466, 0.0464, 0.2020, 0.4800, 0.4030, 0.0354,
        0.5715])

In [ ]:
x.reshape(2, 5)

tensor([[0.5576, 0.7788, 0.1189, 0.0466, 0.0464],
        [0.2020, 0.4800, 0.4030, 0.0354, 0.5715]])

In [ ]:
z = x.view(2, 5)
z

tensor([[0.5576, 0.7788, 0.1189, 0.0466, 0.0464],
        [0.2020, 0.4800, 0.4030, 0.0354, 0.5715]])

In [ ]:
z[:, 0] = 5
z

tensor([[5.0000, 0.7788, 0.1189, 0.0466, 0.0464],
        [5.0000, 0.4800, 0.4030, 0.0354, 0.5715]])

In [ ]:
x

tensor([5.0000, 0.7788, 0.1189, 0.0466, 0.0464, 5.0000, 0.4800, 0.4030, 0.0354,
        0.5715])

In [ ]:
torch.stack([x, x]).shape

torch.Size([2, 10])

# 28. Squeezing, Unsqueezing and Permuting

In [ ]:
z.shape

torch.Size([2, 5])

In [ ]:
z.reshape(1, 2, 5)

tensor([[[5.0000, 0.7788, 0.1189, 0.0466, 0.0464],
         [5.0000, 0.4800, 0.4030, 0.0354, 0.5715]]])

In [ ]:
z.reshape(1, 2, 5).squeeze()

tensor([[5.0000, 0.7788, 0.1189, 0.0466, 0.0464],
        [5.0000, 0.4800, 0.4030, 0.0354, 0.5715]])

In [ ]:
z.unsqueeze(0)

tensor([[[5.0000, 0.7788, 0.1189, 0.0466, 0.0464],
         [5.0000, 0.4800, 0.4030, 0.0354, 0.5715]]])

In [ ]:
z.permute(1, 0)

tensor([[5.0000, 5.0000],
        [0.7788, 0.4800],
        [0.1189, 0.4030],
        [0.0466, 0.0354],
        [0.0464, 0.5715]])

# 29. Selecting Data from Tensors

In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[0:, 1:2, 1:]

tensor([[[5, 6]]])

# 30. Pytorch and NumPy

In [ ]:
import numpy as np

In [ ]:
x.numpy()

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [ ]:
torch.from_numpy(np.arange(10))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 31. PyTorch Reproducability

In [ ]:
torch.rand(3, 3)

tensor([[0.8001, 0.3967, 0.1924],
        [0.0738, 0.6712, 0.9960],
        [0.6795, 0.2606, 0.0897]])

In [ ]:
torch.rand(3, 3)

tensor([[0.7216, 0.0034, 0.6466],
        [0.5187, 0.7133, 0.1822],
        [0.0982, 0.9598, 0.7979]])

In [ ]:
torch.manual_seed(96)
torch.rand(3, 3)

tensor([[0.9598, 0.6580, 0.8326],
        [0.3751, 0.2123, 0.9712],
        [0.3934, 0.8419, 0.9611]])

# 32. Different ways of accessing GPU

In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [ ]:
torch.cuda.device_count()

0