In [10]:
from sklearn.model_selection import train_test_split
import torch
from torch import nn

torch.__version__

'2.0.1+cu118'

# 37. Creating a Dataset with Linear Regression

In [14]:
weight, bias = 0.7, 0.3

X = torch.arange(0, 1, 0.02).unsqueeze(dim=1)
y = weight * X + bias

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
x_train.shape, x_test.shape

(torch.Size([40, 1]), torch.Size([10, 1]))

# 40. Creating our first PyTorch Model

In [2]:
class LinearRegressionModel(nn.Module):

    def __init__(self):

        super().__init__()

        self.weights = nn.Parameter(
            torch.randn(1, requires_grad=True, dtype=torch.float32))

        self.bias = nn.Parameter(
            torch.randn(1, requires_grad=True, dtype=torch.float32))

    def forward(self, x: torch.Tensor) -> torch.Tensor:

        """ Linear Regression Formula Forward Method """

        return self.weights * x + self.bias

# 43. Checking out the Internals of PyTorch Model

In [53]:
torch.manual_seed(42)

model_0 = LinearRegressionModel()
list(model_0.parameters())

[Parameter containing:
 tensor([0.3367], requires_grad=True),
 Parameter containing:
 tensor([0.1288], requires_grad=True)]

In [54]:
model_0.state_dict()

OrderedDict([('weights', tensor([0.3367])), ('bias', tensor([0.1288]))])

# 44. Making Predictions using Inference Mode

In [13]:
# Disables tracking all the gradient values
# PyTorch will track fewer values

with torch.inference_mode():  # torch.no_grad()
    y_preds = model_0(x_test)

y_preds

tensor([[0.3443],
        [0.2770],
        [0.2029],
        [0.1490],
        [0.3982],
        [0.3510],
        [0.4453],
        [0.3241],
        [0.4251],
        [0.3039]])

# 46. Setting up an Optimizer and Loss Function

In [55]:
loss_fn = nn.L1Loss()
optim = torch.optim.SGD(model_0.parameters(), lr=0.01)

# 48. PyTorch Training Loop

In [56]:
epochs = 100

for epoch in range(epochs):

    model_0.train()

    # 1. Forward Pass
    y_pred = model_0(x_train)

    # 2. Calculate the loss
    loss = loss_fn(y_pred, y_train)

    # 3. Zero the gradients of the optimizer
    optim.zero_grad()

    # 4. Perform Backpropagation
    loss.backward()

    # 5. Progress / step the optimizer (gradient descent)
    optim.step()

    model_0.eval()

    if epoch % 10 == 0:

        with torch.inference_mode():
            test_pred = model_0(x_test)
            test_loss = loss_fn(test_pred, y_test)

        print(f'{epoch=} {loss=} {test_loss=}')
        print(model_0.state_dict())

epoch=0 loss=tensor(0.3679, grad_fn=<MeanBackward0>) test_loss=tensor(0.2628)
OrderedDict([('weights', tensor([0.3421])), ('bias', tensor([0.1388]))])
epoch=10 loss=tensor(0.2386, grad_fn=<MeanBackward0>) test_loss=tensor(0.1475)
OrderedDict([('weights', tensor([0.3963])), ('bias', tensor([0.2388]))])
epoch=20 loss=tensor(0.1139, grad_fn=<MeanBackward0>) test_loss=tensor(0.0470)
OrderedDict([('weights', tensor([0.4502])), ('bias', tensor([0.3348]))])
epoch=30 loss=tensor(0.0561, grad_fn=<MeanBackward0>) test_loss=tensor(0.0424)
OrderedDict([('weights', tensor([0.4968])), ('bias', tensor([0.3878]))])
epoch=40 loss=tensor(0.0430, grad_fn=<MeanBackward0>) test_loss=tensor(0.0523)
OrderedDict([('weights', tensor([0.5278])), ('bias', tensor([0.3998]))])
epoch=50 loss=tensor(0.0382, grad_fn=<MeanBackward0>) test_loss=tensor(0.0495)
OrderedDict([('weights', tensor([0.5481])), ('bias', tensor([0.3923]))])
epoch=60 loss=tensor(0.0337, grad_fn=<MeanBackward0>) test_loss=tensor(0.0445)
OrderedDic